name: CI

on:
  push:
    branches: [main, master]
    tags: '*'
  pull_request:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - {name: 'Python 3.12', python: '3.12', os: ubuntu-latest}
          - {name: 'Python 3.11', python: '3.11', os: ubuntu-latest}
          - {name: 'Python 3.10', python: '3.10', os: ubuntu-latest}
          - {name: 'Python 3.9', python: '3.9', os: ubuntu-latest}
          - {name: 'Python 3.8', python: '3.8', os: ubuntu-latest}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies
        run: poetry install

      - name: Install tesseract
        run: sudo apt-get -y update && sudo apt-get install -y tesseract-ocr tesseract-ocr-fra

      - name: Print tesseract version
        run: tesseract --version

      - name: Build project
        run: poetry build

      - name: Run date_detection.py
        run: poetry run python lin_py/date_detection.py

      - name: Run image_processing.py
        run: poetry run python lin_py/image_processing.py

      - name: Run text_extraction.py
        run: poetry run python lin_py/text_extraction.py
